name: Selenium WebDriver CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Restore dependencies
      run: dotnet restore SeleniumBasicExercise.sln

    - name: Build the solution
      run: dotnet build SeleniumBasicExercise.sln --configuration Debug --no-restore

    - name: List contents of TestProject1 directory
      run: ls -la /home/runner/work/CI-System-with-SeleniumWebDriver-demo/CI-System-with-SeleniumWebDriver-demo/TestProject1/bin/Debug/net6.0/

    - name: List contents of TestProject2 directory
      run: ls -la /home/runner/work/CI-System-with-SeleniumWebDriver-demo/CI-System-with-SeleniumWebDriver-demo/TestProject2/bin/Debug/net6.0/

    - name: List contents of TestProject3 directory
      run: ls -la /home/runner/work/CI-System-with-SeleniumWebDriver-demo/CI-System-with-SeleniumWebDriver-demo/TestProject3/bin/Debug/net6.0/

    - name: Run TestProject1 tests
      env:
        CHROMEWEBDRIVER: /usr/bin/google-chrome
      run: dotnet test TestProject1/TestProject1.csproj --verbosity normal

    - name: Run TestProject2 tests
      env:
        CHROMEWEBDRIVER: /usr/bin/google-chrome
      run: dotnet test TestProject2/TestProject2.csproj --verbosity normal

    - name: Run TestProject3 tests
      env:
        CHROMEWEBDRIVER: /usr/bin/google-chrome
      run: dotnet test TestProject3/TestProject3.csproj --verbosity normal
