name: Selenium WebDriver CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install dependencies
      run: dotnet restore SeleniumBasicExercise.sln

    - name: Build
      run: dotnet build SeleniumBasicExercise.sln --configuration Debug --no-restore

      
    - name: Debugging - List higher-level directories
      run: |
        echo "Listing contents of SeleniumIDE directory:"
        ls -la /home/runner/work/CI-System-with-SeleniumWebDriver-demo/CI-System-with-SeleniumWebDriver-demo/SeleniumIDE/
        echo "Listing contents of bin directory:"
        ls -la /home/runner/work/CI-System-with-SeleniumWebDriver-demo/CI-System-with-SeleniumWebDriver-demo/SeleniumIDE/bin/
        echo "Listing contents of Debug directory (if it exists):"
        ls -la /home/runner/work/CI-System-with-SeleniumWebDriver-demo/CI-System-with-SeleniumWebDriver-demo/SeleniumIDE/bin/Debug/ || echo "Debug directory does not exist"


    - name: Debugging - List output directories
      run: |
        echo "Listing contents of Debug directory:"
        ls -la /home/runner/work/CI-System-with-SeleniumWebDriver-demo/CI-System-with-SeleniumWebDriver-demo/SeleniumIDE/bin/Debug/net6.0/
        echo "Listing contents of selenium-manager directory:"
        ls -la /home/runner/work/CI-System-with-SeleniumWebDriver-demo/CI-System-with-SeleniumWebDriver-demo/SeleniumIDE/bin/Debug/net6.0/selenium-manager/
        
    - name: Set execute permissions for selenium-manager
      run: chmod +x /home/runner/work/CI-System-with-SeleniumWebDriver-demo/CI-System-with-SeleniumWebDriver-demo/SeleniumIDE/bin/Debug/net6.0/selenium-manager/linux/selenium-manager || echo "File not found, skipping chmod"

    - name: Run TestProject1 test
      env:
        CHROMEWEBDRIVER: /usr/bin/google-chrome
      run: |
        echo "Running TestProject1 tests"
        dotnet test TestProject1/TestProject1.csproj --verbosity normal
        
    - name: Run TestProject2 test
      env:
        CHROMEWEBDRIVER: /usr/bin/google-chrome
      run: |
        echo "Running TestProject2 tests"
        dotnet test TestProject2/TestProject2.csproj --verbosity normal
        
    - name: Run TestProject3 test
      env:
        CHROMEWEBDRIVER: /usr/bin/google-chrome
      run: |
        echo "Running TestProject3 tests"
        dotnet test TestProject3/TestProject3.csproj --verbosity normal
